version: '3'
services:
  proto:
    command: ./proto/scripts/protoc.sh
    build:
      context: .
      dockerfile: DockerfileProto
    volumes:
      - .:/proto
  server:
    image: echo-server:v1
    build:
      context: server
      dockerfile: Dockerfile
    container_name: echo-server
    ports:
      - "9090:9090"
    depends_on:
      - proto
  envoy:
    image: envoy-proxy:v1
    build:
      context: envoy
      dockerfile: Dockerfile
    container_name: envoy-proxy
    ports:
      - "8080:8080"
      - "9901:9901"
      - "8081:8081"
  client:
    image: echo-client:v1
    build:
      context: client
      dockerfile: Dockerfile
    container_name: echo-client
    depends_on:
      - proto
    ports:
      - "80:80"
