version: '3'
services:
  proto:
    command: ./proto/scripts/protoc.sh
    build:
      context: .
      dockerfile: DockerfileProto
    volumes:
      - .:/proto
  server:
    image: asia-northeast1-docker.pkg.dev/grpc-web-sample/echo/server:v1
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - proto
  envoy:
    image: asia-northeast1-docker.pkg.dev/grpc-web-sample/echo/envoy:v1
    build:
      context: envoy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9901:9901"
      - "8081:8081"
#    links:
#      - server
  client:
    image: asia-northeast1-docker.pkg.dev/grpc-web-sample/echo/client:v1
    build:
      context: client
      dockerfile: Dockerfile
    depends_on:
      - proto
    ports:
      - "3000:3000"
