apiVersion: v1
kind: Service
metadata:
  name: echo-client
  labels:
    app: react
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: react
    tier: frontend
