apiVersion: v1
kind: Service
metadata:
  name: envoy-proxy
  labels:
    app: envoy
    tier: proxy
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: grpc-web
    - port: 8081
      name: grpc
    - port: 9901
      name: admin
  selector:
    app: envoy
    tier: proxy
