apiVersion: v1
kind: Service
metadata:
  name: echo-server
  labels:
    app: echo
    tier: backend
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: echo
    tier: backend
