apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  labels:
    app: echo
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
        tier: backend
    spec:
      containers:
        - name: server
          image: "asia-northeast1-docker.pkg.dev/grpc-web-sample/echo/server:v1"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 9090
